replicaCount: 1

image:
  repository: vishalvn2003492/docscan
  tag: v1

env:
  FLASK_SECRET_KEY: 'strong_secret_key'

service:
  type: ClusterIP
  port: 80

cronJob:
  enabled: true
  schedule: "0 0 * * *"