apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-scanner
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: document-scanner
  template:
    metadata:
      labels:
        app: document-scanner
    spec:
      containers:
        - name: document-scanner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
